### ISSUE TITLE
Attach to existing node

### ISSUE THREAD

**Issue by joho1968** [dmuy/duDialog#10]
Maybe I'm missing something (hopefully), but it'd be nice to be able to initialize a duDialog modal by passing an existing node/ID/whatever to it. Much like **jQuery UI Dialog** has with this construct:

```
$( ".selector" ).dialog({
  modal: true
});
```

This is useful if you want to do something more "persistent" with the dialog/modal while it's being displayed, like allow file browsing/file selection/etc.

**Comment by dmuy** [comment]
Hi @joho1968,

It's unfortunate that this is not the intended use of this library - the library creates its own elements so this would be impossible. I made it like this to have more control over the elements inside the dialog (i.e. dialog buttons). But most of all this was intended for message dialogs & item selections.

Currently, the library allows you to place an HTML content on the dialog, but not from an existing one.

**Comment by joho1968** [comment]
Yes, I figured as much. That is unfortunate indeed. The user (of your package) can of course "easily" circumvent this by creating the content in a variable and then insert the variable, but it's a bit "tedious". I'm not complaining, it was just a suggestion. I think many "jQuery developers" are looking for things to replace existing jQuery components, and jQuery UI Dialog is quite useful in how it works.

Keep up the great work though, it looks great.

**Comment by dmuy** [comment]
I will consider this as an enhancement on future updates. Thanks
