### ISSUE TITLE
hideOnAction without any functionality

### ISSUE THREAD

**Issue by VARGA-Peter** [dmuy/duDialog#13]
`hideOnAction` seems to be not implemented yet. This would be the solution for this request: https://github.com/dmuy/duDialog/issues/11

**Comment by dmuy** [comment]
Hi @VARGA-Peter,

Sorry this took too long to be published, I've actually implemented this way back Nov 27, 2021, but haven't published it. Now, this is available on [version 1.1.4](https://github.com/dmuy/duDialog/releases/tag/v1.1.4)
