### ISSUE TITLE
Feature request: [ ] Don't show again checkbox

### ISSUE THREAD

**Issue by VARGA-Peter** [dmuy/duDialog#14]
I see, that it's not possible to show the check boxes and a text. It would be nice so for example the option _Don't show again_ could be implemented for any shown dialog box.

**Comment by dmuy** [comment]
Hi @VARGA-Peter,

It's possible to show a checkbox and a text/label, but you'll have to set the content as html and manually style the DOM. But for convenience, I've implemented this on [version 1.1.4](https://github.com/dmuy/duDialog/releases/tag/v1.1.4)
