### ISSUE TITLE
YES_NO_CANCEL button types?

### ISSUE THREAD

**Issue by ypark768** [dmuy/duDialog#2]
Thanks for the great library.  I need three buttons type and it seems that current library only offers up to two buttons with OK_CANCEL.  Could you add additional button type: YES_NO_CANCEL on next upgrade?  Thanks again,

**Comment by dmuy** [comment]
Implemented on https://github.com/dmuy/duDialog/commit/a8c1c2df899e24b4c12e2fc67b0617a316e32b77
